import type { Metadata } from "next";
import { Roboto, Lora } from "next/font/google";
import "./globals.css";

// Load the fonts
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],  // Include weights you need
});

const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "700"],  // Include weights you need
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>{`
          body {
            font-family: ${roboto.style.fontFamily}, ${lora.style.fontFamily}, sans-serif;
          }
        `}</style>
      </head>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
